site_name: java-tron
site_url: https://tronprotocol.github.io/documentation-zh/
repo_url: https://github.com/tronprotocol/documentation-zh

nav:
    - 入门: 
        - java-tron入门: 'getting_started/getting_started_with_javatron.md'
    - 使用java-tron:
        - 部署java-tron: using_javatron/installing_javatron.md
        - 备份和恢复: using_javatron/backup_restore.md
        - 轻节点: developers/litefullnode.md
        - 私链网络: using_javatron/private_network.md
        - 事件订阅: architecture/event.md
        - 数据库配置: architecture/database.md
        - 网络配置: using_javatron/connecting_to_tron.md
        - 节点监控: using_javatron/metrics.md
        - 节点维护工具: using_javatron/toolkit.md
    - API 接口:
        - HTTP 接口: api/http.md
        - gRPC 接口: api/rpc.md
    - 核心协议:
        - 波场共识: introduction/dpos.md
        - 超级代表: mechanism-algorithm/sr.md
        - 账户模型: mechanism-algorithm/account.md
        - 资源模型: mechanism-algorithm/resource.md
        - 智能合约: contracts/contract.md
        - 系统合约: mechanism-algorithm/system-contracts.md
        - 去中心化交易所: mechanism-algorithm/dex.md
        - 账户权限管理: mechanism-algorithm/multi-signatures.md
    - java-tron开发: 
        - 开发者指南: developers/java-tron.md
        - TIPs工作流程: developers/tips.md
        - Issue工作流程: developers/issue-workflow.md
        - 治理流程: developers/governance.md
        - 配置IDE开发环境: developers/run-in-idea.md
        - 开发示例: developers/demo.md
        - 核心模块: developers/code-structure.md
    - Dapp开发:
        - Dapp开发工具: contracts/compiler.md
    - Wallet-cli: 
        - 什么是Wallet-Cli: clients/wallet-cli.md
        - Wallet命令: clients/wallet-cli-command.md
    - 版本发布:
        - 新版本部署手册: releases/upgrade-instruction.md
        - 一致性检验: releases/signature_verification.md
        - 历史版本: releases/history.md
    - 术语表: glossary.md

theme:
  name: material
  features:
    - navigation.tabs  # 启用顶部导航栏
    - navigation.sections  # 启用左侧导航栏的分组
    - search.highlight  # 搜索时高亮匹配内容
    - search.suggest  # 搜索时显示建议
    - content.code.annotate  # 代码块注释
    - content.tooltips  # 内容中的工具提示
  palette:
    primary: indigo  # 主色调
    accent: blue  # 强调色
  font:
    text: Roboto  # 正文字体
    code: Roboto Mono  # 代码字体

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - admonition
    - footnotes
    - codehilite
    - toc:
        permalink: true
        toc_depth: 4
    - pymdownx.arithmatex
    - pymdownx.tilde
    - pymdownx.tasklist
    - pymdownx.superfences

plugins:
  - search:
     separator: '[\s\u200b\-]'  
  - exclude:
      glob:
        - clients/tron-grid.md
        - contracts/trc20.md
        - contracts/tvm.md
        - developers/archive-manifest.md
        - developers/contribution.md
        - developers/gpg.md
        - developers/incentives.md
        - developers/resources.md
        - faq/index.md
        - introduction/index.md
        - introduction/overview.md
        - mechanism-algorithm/shielded-TRC20-contract.md
        - mechanism-algorithm/trc10.md

